### ISSUE TITLE
API MVP to utilize Amazon OpenSearch Serverless

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry-api#424]
## 💡 Description

- [x] Identifier resolvers
- [x] Search query q
- [ ] ~Keyword search~ (see also https://github.com/NASA-PDS/registry-api/issues/430)
- [x] Pagination
- [x] Membership (see also https://github.com/NASA-PDS/registry-api/issues/298)
- [x] classes endpoints supporting q , and only showing latest products
- [x] ~properties~ - @jordanpadams  - I don't think this is absolutely necessary for an MVP if we can't get to it
- [ ] ~healthcheck~ - @jordanpadams  - I don't think this is absolutely necessary for an MVP if we can't get to it

### Must-have
- https://github.com/NASA-PDS/registry-api/issues/511
- https://github.com/NASA-PDS/registry-api/issues/503
- https://github.com/NASA-PDS/registry-api/issues/426
- https://github.com/NASA-PDS/registry-api/issues/488
- https://github.com/NASA-PDS/registry-api/issues/516
- https://github.com/NASA-PDS/registry-sweepers/issues/120
- https://github.com/NASA-PDS/registry-api/issues/520

#### Support for Latest Version of Products Only
- #484
- #485
- #486
- #487
- #488

#### Support basic comparators with `q=`
- #494
- #497
- #298

#### Support for `q=` Across All Endpoints
- #490
- #491
- #492
- #493

#### Could-have
- https://github.com/NASA-PDS/registry-api/issues/506
- https://github.com/NASA-PDS/registry-api/issues/507
- https://github.com/NASA-PDS/registry-api/issues/433

**Comment by tloubrieu-jpl** [comment]
Checked tasks so far per https://github.com/NASA-PDS/registry-api/issues/470

**Comment by tloubrieu-jpl** [comment]
@alexdunnjpl ,

I assigned this ticket to you since the already made development, on develop branch are assigned to ticket #470.

**Comment by jordanpadams** [comment]
Status: @alexdunnjpl starting to dig into this design and upgrade

**Comment by tloubrieu-jpl** [comment]
@alexdunnjpl is making progress on membership end-points.

**Comment by alexdunnjpl** [comment]
Membership item implemented in #499 and https://github.com/NASA-PDS/registry/pull/298

Moving on to keyword search

**Comment by alexdunnjpl** [comment]
@jordanpadams @tloubrieu-jpl per https://github.com/NASA-PDS/registry-api/issues/430#issuecomment-2244992218, which requirement should be my next priority?

[This'n?](https://github.com/NASA-PDS/registry-api/issues/351)  Is that actually blocking our deployment to serverless, given that we didn't already have it?

**Comment by jordanpadams** [comment]
@alexdunnjpl probably this parent task: https://github.com/NASA-PDS/registry-api/issues/420, more specifically https://github.com/NASA-PDS/registry-api/issues/425. This will require an update to the product data types to support this. I don't know which requirements are yet to be implemented, but I will try to dig through that later this week.

**Comment by jordanpadams** [comment]
📆 07/2024 status: New tasks split from NASA-PDS/registry#185 but very tightly coupled. In work. On schedule for 8/22

**Comment by jordanpadams** [comment]
Stand-up status: Nearing completion. 1 task remaining for a stable release.

**Comment by jordanpadams** [comment]
All must-have MVP requirements implemented and presented to API WG.
